### ISSUE TITLE
ResolverContract instantiation failure when using defaultAbi

### ISSUE THREAD

**Issue by marcosmartinez7** [rnsdomains/rns-js-resolver#2]
Hi,

ResolverContract is currently receiving a `resolverAbi ` param that must be string.

`Web3.eth.Contract` expects an `Object `as constructor parameter, also, since the ABI generaly is into json format (truffle and other frameworks), probably it would be better to just expect a json object.

By the way, if you dont specify the `resolverAbi `to the resolver, it will use `defaultAbi`. The default one is a json file and it fails when trying to convert it again to an object (cannot parse an object).

```javascript
class ResolverContract {

/**
     * Constructor.
     * @param {string} nodeProvider A web3 provider to use to communicate with the blockchain. Defaults to the public RSK node.
	 * @param {string} resolverAddress The address of the RNS Resolver. Defaults to the public RNS Resolver.
	 * @param {string} resolverAbi The abi of the RNS Resolver. Defaults to the public RNS Resolver's abi.
	 * @returns {ResolverContract} 
     */

	constructor(nodeProvider = defaultNode, resolverAddress = defaultResolverAddress, resolverAbi = defaultAbi){
		this.web3 = new Web3(nodeProvider);
		this.address = resolverAddress;	
		this.abi = resolverAbi;
                // the JSON.parse fails when using defaultAbi since it is a json object already
		this.resolverContract = new this.web3.eth.Contract(JSON.parse(this.abi), this.address);
	}
}
```

**Comment by sebastinez** [comment]
Hello,

Please consider to push a hotfix or minor release to npm, to include this contribution in the SDK Library.

Another topic is it posible that the defaultResolverAddress is out of date? After a reset of the public testnet?
```
const defaultResolverAddress = "0x59313581e7d735793962e16b8d0b10636bf53ae7"
```

According to https://docs.rns.rifos.org/RNS-Testnet/ the testnet resolver contract is 0x480fee7506db34dde84cfec85057a6bd96b38e1b
If that's the case I could do a small PR to correct this.

Thank you very much!

**Comment by ilanolkies** [comment]
Hi @sebastinez! PRs are always welcomed! You are right, the testnet address is wrong.
